name: Android Instrumented Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: 31.0.0
          target: google_apis

      - name: Start AVD
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_5
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest --info

      - name: Upload Android Test Report
        uses: actions/upload-artifact@v3
        with:
          name: android-test-report
          path: app/build/reports/androidTests/connected/
