name: Android Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64" "platforms;android-30"

      - name: Create Android Emulator
        run: echo no | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" -d "pixel"

      - name: Start Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-snapshot-load -noaudio -no-boot-anim -accel auto -gpu swiftshader &

      - name: Wait for Emulator to Boot
        run: adb wait-for-device

      - name: Run Instrumented Tests
        run: ./gradlew connectedDebugAndroidTest --stacktrace

      - name: Stop Emulator
        run: adb -s emulator-5554 emu kill
